export const currencies = {
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 1.0 },
  USD: { code: 'USD', name: 'US Dollar', symbol: '$', rate: 0.21 },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', rate: 0.19 },
  CNY: { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rate: 1.52 },
  JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 32.14 },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 0.32 },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 1.64 },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 0.28 },
  KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', rate: 286.5 },
  INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', rate: 17.5 },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rate: 0.35 },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', rate: 6.78 },
  THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 7.7 },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 3375 },
  PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rate: 11.8 },
  VND: { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rate: 5320 },
  MOP: { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', rate: 1.69 },
  BND: { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', rate: 0.28 },
  KHR: { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', rate: 855 },
  LAK: { code: 'LAK', name: 'Lao Kip', symbol: '₭', rate: 4400 },
  MMK: { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', rate: 440 },
  KPW: { code: 'KPW', name: 'North Korean Won', symbol: '₩', rate: 189 },
  MNT: { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', rate: 710 },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', rate: 58.5 },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', rate: 23 },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', rate: 63 },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', rate: 28 },
  AFN: { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', rate: 15 },
  MVR: { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', rate: 3.2 },
  BTN: { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', rate: 17.5 },
  FJD: { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', rate: 0.47 },
  PGK: { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', rate: 0.8 },
  SBD: { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', rate: 1.7 },
  VUV: { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', rate: 25 },
  WST: { code: 'WST', name: 'Samoan Tālā', symbol: 'WS$', rate: 0.58 },
  TOP: { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', rate: 0.5 },
  XPF: { code: 'XPF', name: 'French Pacific Franc', symbol: 'F', rate: 23.3 },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', rate: 94 },
  UZS: { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', rate: 2650 },
  TMT: { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', rate: 0.74 },
  KGS: { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', rate: 18.7 },
  TJS: { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', rate: 2.3 },
  RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', rate: 19.5 },
  IRR: { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', rate: 8850 },
  SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', rate: 0.79 },
  AED: { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', rate: 0.77 },
  ILS: { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', rate: 0.78 },
  TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rate: 6.8 },
  QAR: { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', rate: 0.76 },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', rate: 0.065 },
  OMR: { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', rate: 0.081 },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', rate: 0.15 },
};
